<!DOCTYPE html>
<html lang="en" class="scroll-smooth">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Auto-testing Report generated by UAM">
    <meta name="author" content="Kenneth Ma (2015), Sadra Setarehdan (2025)">
    <title>{{ result.name }} Auto-Testing Report</title>

    <!-- Tailwind CSS -->
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            darkMode: 'class',
            theme: {
                extend: {
                    colors: {
                        primary: { 50: '#f0f9ff', 100: '#e0f2fe', 200: '#bae6fd', 300: '#7dd3fc', 400: '#38bdf8', 500: '#0ea5e9', 600: '#0284c7', 700: '#0369a1', 800: '#075985', 900: '#0c4a6e' },
                        success: { 50: '#f0fdf4', 100: '#dcfce7', 200: '#bbf7d0', 300: '#86efac', 400: '#4ade80', 500: '#22c55e', 600: '#16a34a', 700: '#15803d', 800: '#166534', 900: '#14532d' },
                        warning: { 50: '#fffbeb', 100: '#fef3c7', 200: '#fde68a', 300: '#fcd34d', 400: '#fbbf24', 500: '#f59e0b', 600: '#d97706', 700: '#b45309', 800: '#92400e', 900: '#78350f' },
                        danger: { 50: '#fef2f2', 100: '#fee2e2', 200: '#fecaca', 300: '#fca5a5', 400: '#f87171', 500: '#ef4444', 600: '#dc2626', 700: '#b91c1c', 800: '#991b1b', 900: '#7f1d1d' },
                    }
                }
            }
        }
    </script>

    <!-- Bootstrap 5 (for table functionality) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">

    <!-- Lucide Icons -->
    <script src="https://unpkg.com/lucide@latest"></script>

    <style>
        * { font-family: 'Inter', sans-serif; }
        
        body {
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%);
            min-height: 100vh;
        }

        .glass-card {
            background: rgba(30, 41, 59, 0.7);
            backdrop-filter: blur(12px);
            border: 1px solid rgba(148, 163, 184, 0.1);
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
        }

        .gradient-text {
            background: linear-gradient(135deg, #38bdf8 0%, #818cf8 50%, #c084fc 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }

        .stat-card {
            background: linear-gradient(135deg, rgba(56, 189, 248, 0.1) 0%, rgba(129, 140, 248, 0.1) 100%);
            border: 1px solid rgba(148, 163, 184, 0.2);
            transition: all 0.3s ease;
        }

        .stat-card:hover {
            transform: translateY(-4px);
            box-shadow: 0 20px 40px -12px rgba(56, 189, 248, 0.3);
            border-color: rgba(56, 189, 248, 0.4);
        }

        /* Bootstrap Table Overrides */
        .bootstrap-table .fixed-table-container { background: transparent !important; border: none !important; }
        .bootstrap-table .fixed-table-body { background: rgba(30, 41, 59, 0.5) !important; }
        .table { --bs-table-bg: transparent; --bs-table-color: #e2e8f0; --bs-table-border-color: rgba(148, 163, 184, 0.2); }
        .table > :not(caption) > * > * { background: transparent !important; color: #e2e8f0; border-color: rgba(148, 163, 184, 0.15); padding: 1rem; }
        .table thead th { background: rgba(15, 23, 42, 0.8) !important; color: #94a3b8; font-weight: 600; text-transform: uppercase; font-size: 0.75rem; letter-spacing: 0.05em; border-bottom: 2px solid rgba(56, 189, 248, 0.3) !important; }
        .table tbody tr:hover > * { background: rgba(56, 189, 248, 0.1) !important; }
        .table-success, .table-success > td, .table-success > th, .success { background: rgba(34, 197, 94, 0.2) !important; color: #86efac !important; }
        .table-warning, .table-warning > td, .table-warning > th { background: rgba(245, 158, 11, 0.2) !important; color: #fcd34d !important; }
        .table-danger, .table-danger > td, .table-danger > th, .danger { background: rgba(239, 68, 68, 0.2) !important; color: #fca5a5 !important; }
        .fixed-table-toolbar .search input { background: rgba(30, 41, 59, 0.8) !important; border: 1px solid rgba(148, 163, 184, 0.3) !important; color: #e2e8f0 !important; border-radius: 0.5rem !important; padding: 0.5rem 1rem !important; }
        .fixed-table-toolbar .search input:focus { border-color: #38bdf8 !important; box-shadow: 0 0 0 3px rgba(56, 189, 248, 0.2) !important; outline: none !important; }
        .fixed-table-toolbar .columns .btn, .fixed-table-toolbar .search .btn { background: rgba(56, 189, 248, 0.2) !important; border: 1px solid rgba(56, 189, 248, 0.3) !important; color: #38bdf8 !important; }
        .fixed-table-pagination { background: transparent !important; }
        .fixed-table-pagination .pagination .page-link { background: rgba(30, 41, 59, 0.8) !important; border-color: rgba(148, 163, 184, 0.2) !important; color: #94a3b8 !important; }
        .fixed-table-pagination .pagination .page-item.active .page-link { background: #0ea5e9 !important; border-color: #0ea5e9 !important; color: white !important; }
        .detail-view { background: rgba(15, 23, 42, 0.6) !important; }
        .detail-icon { color: #38bdf8 !important; }
        .dropdown-menu { background: rgba(30, 41, 59, 0.95) !important; backdrop-filter: blur(12px); border: 1px solid rgba(148, 163, 184, 0.2) !important; }
        .dropdown-item { color: #e2e8f0 !important; }
        .dropdown-item:hover { background: rgba(56, 189, 248, 0.2) !important; }

        /* Scrollbar */
        ::-webkit-scrollbar { width: 8px; height: 8px; }
        ::-webkit-scrollbar-track { background: rgba(30, 41, 59, 0.5); }
        ::-webkit-scrollbar-thumb { background: rgba(148, 163, 184, 0.3); border-radius: 4px; }
        ::-webkit-scrollbar-thumb:hover { background: rgba(148, 163, 184, 0.5); }

        /* Animations */
        @keyframes fadeInUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
        .animate-fade-in-up { animation: fadeInUp 0.6s ease-out forwards; }
        .animate-delay-100 { animation-delay: 0.1s; }
        .animate-delay-200 { animation-delay: 0.2s; }
        .animate-delay-300 { animation-delay: 0.3s; }
    </style>
</head>

<body class="text-slate-200">
    <!-- Header -->
    <header class="sticky top-0 z-50 glass-card border-b border-slate-700/50">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
                <div class="flex items-center gap-3">
                    <div class="p-2 rounded-lg bg-gradient-to-br from-primary-500 to-purple-500">
                        <i data-lucide="file-check-2" class="w-6 h-6 text-white"></i>
                    </div>
                    <div>
                        <h1 class="text-lg font-semibold text-white">UAM Report</h1>
                        <p class="text-xs text-slate-400" id="generated-time">Loading...</p>
                    </div>
                </div>
                <nav class="flex items-center gap-1">
                    <a href="#glance" class="px-4 py-2 text-sm font-medium text-slate-300 hover:text-white hover:bg-white/5 rounded-lg transition-colors flex items-center gap-2">
                        <i data-lucide="bar-chart-3" class="w-4 h-4"></i>
                        Overview
                    </a>
                    <a href="#reports" class="px-4 py-2 text-sm font-medium text-slate-300 hover:text-white hover:bg-white/5 rounded-lg transition-colors flex items-center gap-2">
                        <i data-lucide="users" class="w-4 h-4"></i>
                        Results
                    </a>
                </nav>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <!-- Stats Cards -->
        <section id="glance" class="mb-12 scroll-mt-24">
            <div class="flex items-center gap-3 mb-6 opacity-0 animate-fade-in-up">
                <i data-lucide="pie-chart" class="w-8 h-8 text-primary-400"></i>
                <h2 class="text-3xl font-bold gradient-text">At a Glance</h2>
            </div>
            
            <!-- Summary Stats -->
            <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8 opacity-0 animate-fade-in-up animate-delay-100">
                <div class="stat-card rounded-xl p-5" id="stat-total">
                    <div class="flex items-center justify-between">
                        <div>
                            <p class="text-sm text-slate-400 mb-1">Total Students</p>
                            <p class="text-3xl font-bold text-white" id="total-students">-</p>
                        </div>
                        <div class="p-3 rounded-full bg-primary-500/20">
                            <i data-lucide="users" class="w-6 h-6 text-primary-400"></i>
                        </div>
                    </div>
                </div>
                <div class="stat-card rounded-xl p-5" id="stat-pass">
                    <div class="flex items-center justify-between">
                        <div>
                            <p class="text-sm text-slate-400 mb-1">Passing (>80%)</p>
                            <p class="text-3xl font-bold text-success-400" id="passing-count">-</p>
                        </div>
                        <div class="p-3 rounded-full bg-success-500/20">
                            <i data-lucide="check-circle" class="w-6 h-6 text-success-400"></i>
                        </div>
                    </div>
                </div>
                <div class="stat-card rounded-xl p-5" id="stat-partial">
                    <div class="flex items-center justify-between">
                        <div>
                            <p class="text-sm text-slate-400 mb-1">Partial (1-80%)</p>
                            <p class="text-3xl font-bold text-warning-400" id="partial-count">-</p>
                        </div>
                        <div class="p-3 rounded-full bg-warning-500/20">
                            <i data-lucide="alert-circle" class="w-6 h-6 text-warning-400"></i>
                        </div>
                    </div>
                </div>
                <div class="stat-card rounded-xl p-5" id="stat-fail">
                    <div class="flex items-center justify-between">
                        <div>
                            <p class="text-sm text-slate-400 mb-1">Failing (0%)</p>
                            <p class="text-3xl font-bold text-danger-400" id="failing-count">-</p>
                        </div>
                        <div class="p-3 rounded-full bg-danger-500/20">
                            <i data-lucide="x-circle" class="w-6 h-6 text-danger-400"></i>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Chart -->
            <div class="glass-card rounded-2xl p-6 opacity-0 animate-fade-in-up animate-delay-200">
                <h3 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <i data-lucide="trending-up" class="w-5 h-5 text-primary-400"></i>
                    Grade Distribution
                </h3>
                <div class="relative" style="height: 400px;">
                    <canvas id="distribution-chart"></canvas>
                </div>
            </div>
        </section>

        <!-- Individual Results -->
        <section id="reports" class="scroll-mt-24 opacity-0 animate-fade-in-up animate-delay-300">
            <div class="flex items-center gap-3 mb-6">
                <i data-lucide="list" class="w-8 h-8 text-primary-400"></i>
                <h2 class="text-3xl font-bold gradient-text">Individual Results</h2>
            </div>
            
            <div class="glass-card rounded-2xl p-6 overflow-hidden">
                <table id="table" class="table"></table>
            </div>
        </section>
    </main>

    <!-- Footer -->
    <footer class="border-t border-slate-700/50 mt-12">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
            <p class="text-center text-sm text-slate-500">
                Generated by UAM (Universal Auto-Marker) • 
                <a href="https://github.com" class="text-primary-400 hover:text-primary-300">View on GitHub</a>
            </p>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>

    <script type="text/javascript">
        // Initialize Lucide icons
        lucide.createIcons();
        
        // Trigger animations
        document.querySelectorAll('.opacity-0').forEach((el, i) => {
            setTimeout(() => el.classList.remove('opacity-0'), 100);
        });

        // grades listing
        $(function () {
            var $table = $('#table');

            // construct the main report listing table
            $table.bootstrapTable({
                columns: [[{
                    field: 'student_number',
                    title: 'Student #',
                    sortable: true
                    }, {
                    field: 'name',
                    title: 'Full Name',
                    sortable: true
                    }, {
                    field: 'utorid',
                    title: 'UTORid',
                    sortable: true
                    }, {
                    field: 'email',
                    title: 'Email',
                    sortable: true
                    }, {
                    field: 'source',
                    title: 'Source',
                    sortable: true,
                    visible: false
                    }].concat(testCaseNamesToColumns(tests))],

                data: translateToRows(aggregated),

                // expand each TestCases table
                onExpandRow: function (index, row, $detail) {
                    var columnData = [];
                    var assignmentResults = getRowPasses(aggregated.results[row.id].results, false);

                    for (testCase in assignmentResults) {

                        // skip Total testCase since it already appears as default on main table
                        if (testCase !== 'Total') {
                            columnData.push({
                                testcase: testCase,
                                result: assignmentResults[testCase]
                            });
                        }
                    }

                    $detail.html('<table></table>').find('table').bootstrapTable({
                        columns: [{
                            field: 'testcase',
                            title: 'Test Case'
                            }, {
                            field: 'result',
                            title: 'Results',
                            cellStyle: colourRatio
                            }],

                        data: columnData,
                        detailView: true,
                        sortable: true,
                        striped: true,
                        search: true,
                        searchTimeOut: 0,

                        // expand each TestMethod detailView (showing each method's results)
                        onExpandRow: function (testCaseIndex, testCaseRow, $testCaseDetail) {
                            $testCaseDetail.html('<table></table>').find('table').bootstrapTable({
                                columns: [{
                                    field: 'method',
                                    title: 'Test Method',
                                    cellStyle: colourResult
                                    }],

                                data: function () {
                                    var testMethods = aggregated.results[row.id].results[testCaseRow.testcase];
                                    var columnData = [];

                                    if (testMethods) {
                                        // grab all results and then sort them (or else we have passes always first)
                                        if (testMethods['passes']) {
                                            for (testMethod in testMethods['passes']) {
                                                columnData.push({
                                                    method: testMethod,
                                                    description: testMethods['passes'][testMethod],
                                                    message: '',
                                                    details: '',
                                                    result: 'success'
                                                });
                                            }
                                        }

                                        if (testMethods['failures']) {
                                            for (testMethod in testMethods['failures']) {
                                                columnData.push({
                                                    method: testMethod,
                                                    description: testMethods['failures'][testMethod]['description'],
                                                    message: testMethods['failures'][testMethod]['message'],
                                                    details: testMethods['failures'][testMethod]['details'],
                                                    result: 'danger'
                                                });
                                            }
                                        }

                                        if (testMethods['errors']) {
                                            for (testMethod in testMethods['errors']) {
                                                columnData.push({
                                                    method: testMethod,
                                                    description: testMethods['errors'][testMethod]['description'],
                                                    message: testMethods['errors'][testMethod]['message'],
                                                    details: testMethods['errors'][testMethod]['details'],
                                                    result: 'danger'
                                                });
                                            }
                                        }
                                    } else {
                                        columnData.push({
                                            method: 'Import Error',
                                            description: 'Unable to read Student Assignment',
                                            message: '',
                                            details: '',
                                            result: 'danger'
                                        });
                                    }

                                    // sort results by test method name
                                    return columnData.sort(function (a, b) {
                                        return (a['method'] > b['method']) ? 1 : -1;
                                    });
                                }(),
                                detailView: true,
                                search: true,
                                searchTimeOut: 0,
                                detailFormatter: function (index, row) {
                                    return '<div class="p-4 rounded-lg" style="background: rgba(15, 23, 42, 0.8);">' +
                                        '<p class="mb-2"><span class="text-primary-400 font-semibold">Description:</span> <span class="text-slate-300">' + (row.description ? $('<div>').text(row.description).html() : 'Not provided') + '</span></p>' +
                                        (row.message ? '<p class="mb-2"><span class="text-warning-400 font-semibold">Message:</span> <span class="text-slate-300">' + $('<div>').text(row.message).html() + '</span></p>' : '') +
                                        (row.details ? '<div><span class="text-danger-400 font-semibold">Details:</span><pre class="mt-2 p-3 rounded-lg text-sm text-slate-300 overflow-x-auto" style="background: rgba(0,0,0,0.3);">' + $('<div>').text(row.details).html() + '</pre></div>' : '') +
                                        '</div>';
                                }
                            });
                        }
                    });
                },

                striped: true,
                search: true,
                searchTimeOut: 0,
                detailView: true,
                showColumns: true,
                minimumCountColumns: 1,
                pagination: true,
                pageSize: 25,
                pageList: [10, 25, 50, 100, 'All'],
                iconsPrefix: 'bi',
                icons: {
                    detailOpen: 'bi-plus',
                    detailClose: 'bi-dash'
                }
            });
        });

        // gives BootstrapTable sorter ability to sort grades (that appear as x/y)
        function gradeSorter(a, b) {
            a = parseInt(a.split('/')[0]);
            b = parseInt(b.split('/')[0]);

            if (a > b) return 1;
            else if (a < b) return -1;
            else return 0;
        }

        // takes an aggregated json object and then produces rows the main BootstrapTable
        // used in data for main BootstrapTable
        function translateToRows(report) {
            var rows = [];
            var row;

            for (assignment in report.results) {
                for (student in report.results[assignment].students) {
                    row = $.extend({
                        id: assignment,
                        student_number: report.results[assignment].students[student].student_number,
                        name: report.results[assignment].students[student].last + ', ' + report.results[assignment].students[student].first,
                        utorid: report.results[assignment].students[student].student_id,
                        source: report.results[assignment].origin,
                        email: '<a href="mailto:' + report.results[assignment].students[student].email + '" class="text-primary-400 hover:text-primary-300">' + report.results[assignment].students[student].email + '</a>'
                    }, getRowPasses(report.results[assignment].results, true));

                    rows.push(row);
                }
            }
            return rows;
        }

        // takes an individual assignment results json object and produces testCase names and their passes (in grade x/y format)
        // if trackInGlobals is true, then add results to global grade distribution for charts
        function getRowPasses(assignmentResults, trackInGlobals) {
            var rowPasses = {};
            var passes;
            var total = 0;

            for (testCase in tests) {
                if (testCase !== 'Total') {
                    passes = Object.keys((assignmentResults[testCase] && assignmentResults[testCase].passes) || {}).length;
                    rowPasses[testCase] = passes + '/' + tests[testCase].count;

                    // add to grade distribution (for chart)
                    if (trackInGlobals) tests[testCase].distribution[Math.round(passes / tests[testCase].count * 10)] += 1;

                    // add to total for reconcilation later
                    total += passes;
                }
            }

            rowPasses['Total'] = total + '/' + tests['Total'].count;
            tests['Total'].distribution[Math.round(total / tests['Total'].count * 10)] += 1;
            return rowPasses;
        }

        // reads testCase names from an aggregated report and tracks the testCase in the distribution chart
        function testCaseNames(report) {
            var testCases = {
                'Total': {
                    count: 0,
                    distribution: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                }
            };
            var testCase;
            var total = 0;

            for (test in report.tests) {
                testCase = report.tests[test].split('.').slice(0, 2).join('.');
                if (testCase.indexOf('unittest') == -1) {
                    if (!(testCase in testCases)) {
                        testCases[testCase] = {
                            count: 1,
                            distribution: [
                                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                            ]
                        };
                    } else {
                        testCases[testCase].count += 1;
                    }

                    // add to assignment total
                    testCases['Total'].count += 1;
                }
            }

            return testCases;
        }

        // takes a json object containing testCase names and generates header columns for the main
        // BootstrapTable
        function testCaseNamesToColumns(testCaseNames) {
            var columns = [];
            var column;

            for (testCaseName in testCaseNames) {
                column = {
                    field: testCaseName,
                    title: testCaseName,
                    sortable: true,
                    cellStyle: colourRatio,
                    visible: false,
                    sorter: gradeSorter,
                    pagination: true
                }

                // restore visibility to total column
                if (testCaseName === 'Total') {
                    column['visible'] = true;
                }

                columns.push(column);
            }

            return columns;
        }

        // assigns an appropriate colour for cells that contain grades
        // used in columns for BootstrapTable under cellStyle for cells
        // that contain grades in x/y format
        function colourRatio(value, row, index) {
            var ratio = +value.split('/')[0] / +value.split('/')[1];

            if (ratio > 0.8) {
                return {
                    classes: 'table-success'
                }
            } else if (ratio > 0) {
                return {
                    classes: 'table-warning'
                }
            } else {
                return {
                    classes: 'table-danger'
                }
            }
        }

        // assigns an appropriate colour depending on the row's
        // result value (which is set to some class containing a background
        // colour)
        function colourResult(value, row, index) {
            return {
                classes: row.result
            }
        }

        // Chart.js distribution chart
        $(function () {
            const ctx = document.getElementById('distribution-chart').getContext('2d');
            
            // Prepare datasets
            const datasets = [];
            const colors = [
                { bg: 'rgba(56, 189, 248, 0.6)', border: 'rgb(56, 189, 248)' },
                { bg: 'rgba(192, 132, 252, 0.6)', border: 'rgb(192, 132, 252)' },
                { bg: 'rgba(251, 191, 36, 0.6)', border: 'rgb(251, 191, 36)' },
                { bg: 'rgba(52, 211, 153, 0.6)', border: 'rgb(52, 211, 153)' },
                { bg: 'rgba(248, 113, 113, 0.6)', border: 'rgb(248, 113, 113)' },
                { bg: 'rgba(129, 140, 248, 0.6)', border: 'rgb(129, 140, 248)' },
            ];
            
            let colorIndex = 0;
            for (let testCase in tests) {
                const color = colors[colorIndex % colors.length];
                datasets.push({
                    label: testCase,
                    data: tests[testCase].distribution,
                    backgroundColor: color.bg,
                    borderColor: color.border,
                    borderWidth: 2,
                    borderRadius: 6,
                    hidden: testCase !== 'Total'
                });
                colorIndex++;
            }

            new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['0%', '10%', '20%', '30%', '40%', '50%', '60%', '70%', '80%', '90%', '100%'],
                    datasets: datasets
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            position: 'bottom',
                            labels: {
                                color: '#94a3b8',
                                usePointStyle: true,
                                padding: 20,
                                font: { size: 12 }
                            }
                        },
                        tooltip: {
                            backgroundColor: 'rgba(15, 23, 42, 0.9)',
                            titleColor: '#e2e8f0',
                            bodyColor: '#94a3b8',
                            borderColor: 'rgba(148, 163, 184, 0.2)',
                            borderWidth: 1,
                            padding: 12,
                            cornerRadius: 8,
                            callbacks: {
                                label: function(context) {
                                    return context.dataset.label + ': ' + context.raw + ' students';
                                }
                            }
                        }
                    },
                    scales: {
                        x: {
                            title: {
                                display: true,
                                text: 'Grade (Percentage)',
                                color: '#94a3b8',
                                font: { size: 12, weight: 500 }
                            },
                            grid: { color: 'rgba(148, 163, 184, 0.1)' },
                            ticks: { color: '#94a3b8' }
                        },
                        y: {
                            title: {
                                display: true,
                                text: 'Number of Students',
                                color: '#94a3b8',
                                font: { size: 12, weight: 500 }
                            },
                            grid: { color: 'rgba(148, 163, 184, 0.1)' },
                            ticks: { color: '#94a3b8' },
                            beginAtZero: true
                        }
                    }
                }
            });

            // Update stats cards
            updateStats();
        });

        function updateStats() {
            const totalDist = tests['Total'].distribution;
            const totalStudents = totalDist.reduce((a, b) => a + b, 0);
            const passing = totalDist[9] + totalDist[10]; // 90% and 100%
            const failing = totalDist[0];
            const partial = totalStudents - passing - failing;

            document.getElementById('total-students').textContent = totalStudents;
            document.getElementById('passing-count').textContent = passing;
            document.getElementById('partial-count').textContent = partial;
            document.getElementById('failing-count').textContent = failing;
            
            // Update generated time
            const now = new Date().toISOString().slice(0, 19).replace('T', ' ');
            document.getElementById('generated-time').textContent = 'Generated: ' + now;
        }

        var aggregated = {{ result }};
        var tests = testCaseNames(aggregated);
    </script>
</body>

</html>

