<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Auto-testing Individual Report generated by UAM">
    <meta name="author" content="Kenneth Ma (2015), Sadra Setarehdan (2025)">
    <title>{{ result.assignment }} Individual Auto-Testing Report</title>

    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            darkMode: 'class',
            theme: {
                extend: {
                    colors: {
                        primary: {
                            400: '#38bdf8',
                            500: '#0ea5e9'
                        }
                    }
                }
            }
        }
    </script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <script src="https://unpkg.com/lucide@latest"></script>

    <style>
        * { font-family: 'Inter', sans-serif; }
        body { background: linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%); min-height: 100vh; }
        .glass-card { background: rgba(30,41,59,0.7); backdrop-filter: blur(12px); border: 1px solid rgba(148,163,184,0.1); box-shadow: 0 25px 50px -12px rgba(0,0,0,0.25); }
        .gradient-text { background: linear-gradient(135deg, #38bdf8 0%, #818cf8 50%, #c084fc 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }
        .stat-card { background: linear-gradient(135deg, rgba(56,189,248,0.1) 0%, rgba(129,140,248,0.1) 100%); border: 1px solid rgba(148,163,184,0.2); transition: all 0.3s ease; }
        .stat-card:hover { transform: translateY(-4px); box-shadow: 0 20px 40px -12px rgba(56,189,248,0.3); border-color: rgba(56,189,248,0.4); }
        @keyframes fadeInUp { from { opacity:0; transform: translateY(20px);} to { opacity:1; transform: translateY(0);} }
        .animate-fade-in-up { animation: fadeInUp 0.6s ease-out forwards; }
        .animate-delay-100 { animation-delay: 0.1s; }
        .animate-delay-200 { animation-delay: 0.2s; }
        .animate-delay-300 { animation-delay: 0.3s; }
        pre { white-space: pre-wrap; }
        .accordion-content { display: none; }
        .accordion-content.open { display: block; }
        .accordion-btn svg { transition: transform 0.2s ease; }
        .accordion-btn.open svg { transform: rotate(180deg); }
    </style>
</head>
<body class="text-slate-200">
    <header class="sticky top-0 z-50 glass-card border-b border-slate-700/50">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
                <div class="flex items-center gap-3">
                    <div class="p-2 rounded-lg bg-gradient-to-br from-primary-500 to-purple-500">
                        <i data-lucide="file-text" class="w-6 h-6 text-white"></i>
                    </div>
                    <div>
                        <div class="text-sm text-slate-400">Assignment</div>
                        <div class="text-lg font-semibold text-white">{{ result.assignment }}</div>
                    </div>
                </div>
                <nav class="flex items-center gap-1">
                    <a href="#summary" class="px-4 py-2 text-sm font-medium text-slate-300 hover:text-white hover:bg-white/5 rounded-lg transition-colors flex items-center gap-2">
                        <i data-lucide="info" class="w-4 h-4"></i> Summary
                    </a>
                    <a href="#details" class="px-4 py-2 text-sm font-medium text-slate-300 hover:text-white hover:bg-white/5 rounded-lg transition-colors flex items-center gap-2">
                        <i data-lucide="list" class="w-4 h-4"></i> Details
                    </a>
                </nav>
            </div>
        </div>
    </header>

    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <section id="summary" class="mb-12 scroll-mt-24">
            <div class="flex items-center gap-3 mb-6 opacity-0 animate-fade-in-up">
                <i data-lucide="pie-chart" class="w-8 h-8 text-primary-400"></i>
                <h2 class="text-3xl font-bold gradient-text">Summary</h2>
            </div>

            <div class="glass-card rounded-2xl p-6">
                <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div class="stat-card rounded-xl p-5">
                        <div class="text-sm text-slate-400">Students</div>
                        <div class="text-2xl font-bold text-white">{{ result.students | student_list('%s %s (%s)', ['first','last','student_id']) | join(', ') }}</div>
                    </div>
                    <div class="stat-card rounded-xl p-5">
                        <div class="text-sm text-slate-400">Generated</div>
                        <div class="text-2xl font-bold text-white">{{ result.date }}</div>
                    </div>
                    <div class="stat-card rounded-xl p-5">
                        <div class="text-sm text-slate-400">Passed</div>
                        <div class="text-2xl font-bold text-white">{{ result.results | get_all_counts(0) }} / {{ result.results | get_all_counts(3) }}</div>
                    </div>
                </div>
            </div>
        </section>

        <section id="details" class="scroll-mt-24 opacity-0 animate-fade-in-up animate-delay-200">
            <div class="flex items-center gap-3 mb-6">
                <i data-lucide="list" class="w-8 h-8 text-primary-400"></i>
                <h2 class="text-3xl font-bold gradient-text">Test Details</h2>
            </div>

            <div class="glass-card rounded-2xl p-6 overflow-hidden">
                    {% for test in result.results %}
                    <div class="border border-slate-700/50 rounded-xl overflow-hidden mb-3">
                        <button class="accordion-btn w-full flex items-center justify-between px-4 py-3 bg-slate-800/50 hover:bg-slate-700/50 transition-colors text-left" onclick="this.classList.toggle('open'); this.nextElementSibling.classList.toggle('open');">
                            <div>
                                <span class="text-slate-400">Tests for</span>
                                <span class="font-semibold text-white ml-2">{{ test }}</span>
                                <span class="ml-2 text-slate-400">({{ result.results[test] | get_counts(0) }}/{{ result.results[test] | get_counts(3) }} passed)</span>
                            </div>
                            <i data-lucide="chevron-down" class="w-5 h-5 text-slate-400"></i>
                        </button>
                        <div class="accordion-content px-4 py-3">
                                {% set test_num = [0] %}

                                {% for method in result.results[test].passes %}
                                {% do test_num.insert(0, test_num[0] + 1) %}{% do test_num.pop() %}
                                <div class="flex items-start justify-between gap-4 py-2 border-b border-slate-700/40">
                                    <div class="text-slate-200">
                                        <span class="text-slate-400">{{ test_num[0] }})</span>
                                        <span class="ml-2">{{ ((result.results[test].passes[method] or method) | wordwrap) }}</span>
                                    </div>
                                    <span class="inline-flex items-center px-2 py-1 rounded-lg bg-emerald-500/20 text-emerald-300 border border-emerald-400/40">ok</span>
                                </div>
                                {% endfor %}

                                {% for method in result.results[test].failures %}
                                {% do test_num.insert(0, test_num[0] + 1) %}{% do test_num.pop() %}
                                <div class="py-3 border-b border-slate-700/40">
                                    <div class="flex items-start justify-between gap-4">
                                        <div class="text-slate-200">
                                            <span class="text-slate-400">{{ test_num[0] }})</span>
                                            <span class="ml-2">{{ ((result.results[test].failures[method].description or method) | wordwrap) }}</span>
                                        </div>
                                        <span class="inline-flex items-center px-2 py-1 rounded-lg bg-amber-500/20 text-amber-300 border border-amber-400/40">failed</span>
                                    </div>
                                    <div class="mt-2 text-slate-300">
                                        because {{ result.results[test].failures[method].message }} (details below):
                                    </div>
                                    <pre class="mt-2 p-3 rounded-lg bg-slate-900/60 text-slate-300 border border-slate-700/60">{{ result.results[test].failures[method].details | indent(4, true) }}</pre>
                                </div>
                                {% endfor %}

                                {% for method in result.results[test].errors %}
                                {% do test_num.insert(0, test_num[0] + 1) %}{% do test_num.pop() %}
                                <div class="py-3 border-b border-slate-700/40">
                                    <div class="flex items-start justify-between gap-4">
                                        <div class="text-slate-200">
                                            <span class="text-slate-400">{{ test_num[0] }})</span>
                                            <span class="ml-2">{{ ((result.results[test].errors[method].description or method) | wordwrap) }}</span>
                                        </div>
                                        <span class="inline-flex items-center px-2 py-1 rounded-lg bg-rose-500/20 text-rose-300 border border-rose-400/40">error</span>
                                    </div>
                                    <div class="mt-2 text-slate-300">
                                        because {{ result.results[test].errors[method].message }} (details below):
                                    </div>
                                    <pre class="mt-2 p-3 rounded-lg bg-slate-900/60 text-slate-300 border border-slate-700/60">{{ result.results[test].errors[method].details | indent(4, true) }}</pre>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
        </section>
    </main>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        lucide.createIcons();
        document.querySelectorAll('.opacity-0').forEach((el) => {
            setTimeout(() => el.classList.remove('opacity-0'), 100);
        });
    </script>
</body>
</html>
